name: Deploy to Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Construir imagen con etiqueta latest
        run: |
          docker build -f DockerFile.integration -t esakiback:1.0 .

      - name: Reiniciar contenedor con la nueva imagen
        run: |
          # Fuerza la eliminación del contenedor si existe
          docker rm -f esakiback || true
          # Ejecuta la nueva versión
          docker run -d -p 3100:3100 --name esakiback --restart unless-stopped esakiback:1.0