name: Deploy to Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Especifica que se ejecuta en un runner self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Construir imagen con etiqueta latest
        run: |
          docker build -f DockerFile.vps -t esakiback:latest .

      - name: Eliminar contenedor antiguo
        run: |
          docker rm -f esakiback || true  # Fuerza eliminación si existe

      - name: Limpiar imágenes huérfanas (opcional)
        run: |
          docker image prune -f  # Elimina imágenes sin uso para ahorrar espacio


      - name: Ejecutar nuevo contenedor
        run: |
          docker run -d \
            --name esakiback \
            -p 3100:3100 \
            --restart unless-stopped \
            esakiback:latest