name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: self-hosted # Usará tu VPS como runner
    steps:
      - name: Instalar dependencias de Stripe
        run: npm install stripe@17.4.0

      - name: Instalar dotenv-cli
        run: npm install -g dotenv-cli

      - name: Instalar dependencias del proyecto
        run: npm install

      - name: Construir la aplicación
        run: npm run start:prod
