name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.2.0

      - name: Instalar dependencias de Stripe
        run: npm install stripe@17.4.0

      - name: Instalar dotenv-cli
        run: npm install -g dotenv-cli

      - name: Instalar dependencias del proyecto
        run: npm install

      - name: Construir y ejecutar la aplicación
        run: |
          npm run build
          nohup npm run start:prod > output.log 2>&1 &
          echo $! > .pidfile
          sleep 10

      - name: Verificar si la aplicación está en ejecución
        run: |
          if ps -p $(cat .pidfile) > /dev/null
          then
            echo "La aplicación se está ejecutando correctamente"
          else
            echo "La aplicación no se inició correctamente"
            cat output.log
            exit 1
          fi

      - name: Detener la aplicación
        run: kill $(cat .pidfile)
