name: Deploy to Docker

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: self-hosted  # Especifica que se ejecuta en un runner self-hosted
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        
     
      - name: Stop and remove all containers
        run: |
              docker-compose down --remove-orphans 
        
    
      - name: Ejecutar nuevo contenedor
        run: |
          docker-compose up --build -d