name: CI Pipeline
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.2.0

      - name: Instalar dependencias
        run: npm install --force --verbose


      - name: Preparar archivo de log
        run: |
          sudo touch /home/appback.log
          sudo chown $USER:$USER /home/appback.log

      - name: Detener sesiones anteriores
        run: |
          screen -list | grep -q "esakiback" && screen -XS esakiback quit || true

      - name: Iniciar aplicación con screen
        run: |
          screen -Logfile /home/appback.log -L -dmS esakiback npm run start:prod

      - name: Verificar sesión
        run: |
          sleep 3
          screen -list
          ps aux | grep -q "[n]pm run start:prod" || (echo "¡Error al iniciar!" && exit 1)
