name: CI Pipeline
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.2.0

      - name: Instalar dependencias
        run: npm install --force --verbose

      - name: Verificar y detener instancia previa del servidor
        run: |
          echo "Buscando proceso existente..."
          if pgrep -f "npm run start:prod"; then
            echo "Servidor en ejecución. Deteniendo..."
            pkill -f "npm run start:prod"
            sleep 3
          else
            echo "No se encontró ningún servidor en ejecución."
          fi

      - name: Iniciar servidor en background
        run: |
          npm run start:prod 
   

